name = "personal portfolio"
description = "clean, minimalist hugo theme for personal portfolios"
homepage = "https://github.com/stoicfeats/stoicfeats.github.io"
tags = ["blog", "personal", "portfolio", "minimal", "responsive"]
features = ["responsive", "blog", "portfolio"]
min_version = "0.41.0"

[author]
  name = "stoicfeats"
  homepage = "https://stoicfeats.github.io/"

[original]
  name = "hanwenguo"
  repo = "https://github.com/hanwenguo/hugo-theme-nostyleplease"
